service: rowantree-auth-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  token:
    handler: token_handler.handler
    events:
      - httpApi:
          path: /v1/auth/token
          method: post
  register:
    handler: register_handler.handler
    events:
      - httpApi:
          path: /v1/auth/register
          method: post
